### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by Dunge** [lucky72s/dyypholdem#1]
First of all, your Git LFS account seems locked due to high bandwidth usage. Could it be possible to upload your trained model files elsewhere?

> Downloading data/models/flop/final_cpu.tar (192 MB)
> Error downloading object: data/models/flop/final_cpu.tar (553ee66): Smudge error: Error downloading data/models/flop/final_cpu.tar (553ee66e14ba09946389e9e6f5c277b4ae3410a2a353d3374c91cad6bf46f3a3): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

The second problem is, the ACPC server only include a pre-built binary for Linux. I downloaded the source from the referenced site, but of course including the files in a Visual Studio C++ console project doesn't quite work with Makefile and Linux type of .h includes. Then I tried with Mingw-w64 and of course it does not implement socket.h. So I ended up with MSYS2 and finally managed to get executables (depending on msys-2.0.dll). Of course running the .sh file doesn't work, but running dealer.exe directly with the same arguments do. I can upload the binaries if someone need them.

Then I installed CUDA, Python, PyTorch and the other modules. Another few gigabytes later..

Now I want to run the python players. Using the command on the readme:

> Z:\Holdem\src>python player/manual_acpc_player.py 18901
> usage: manual_acpc_player.py [-h] hostname port
> manual_acpc_player.py: error: the following arguments are required: port

I found out adding the term "port" as a supplement in the argument works:

> Z:\Holdem\src>python player/manual_acpc_player.py port 18901

But then it crash with this error:

> | INFO     | Environment setup complete - initializing...
> | TRACE    | Loading hand ranks lookup table...
> Traceback (most recent call last):
>   File "Z:\Holdem\src\player\manual_acpc_player.py", line 63, in <module>
>     from server.acpc_game import ACPCGame
>   File "Z:\Holdem\src\server\acpc_game.py", line 10, in <module>
>     from game.evaluation.evaluator import Evaluator
>   File "Z:\Holdem\src\game\evaluation\evaluator.py", line 11, in <module>
>     class Evaluator(object):
>   File "Z:\Holdem\src\game\evaluation\evaluator.py", line 24, in Evaluator
>     _texas_lookup = torch.load("./game/evaluation/hand_ranks.pt").type(arguments.LongTensor)
>   File "Z:\Users\dunge\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\torch\serialization.py", line 608, in load
>     return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
>   File "Z:\Users\dunge\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\torch\serialization.py", line 777, in _legacy_load
>     magic_number = pickle_module.load(f, **pickle_load_args)
> _pickle.UnpicklingError: invalid load key, 'v'.

I checked, and the file `./game/evaluation/hand_ranks.pt` does exist. Not sure what's that about an invalid key 'v'. Is it because I'm missing the trained model files?

**Comment by lucky72s** [comment]
Hi!

Sorry for the troubles - I was not aware of the data limits for the LFS downloads. I added more bandwidth, so please clone this repo again to get all the files (it's not only the models, but also some master data like the hand ranks file).

And there was indeed an error in the README with regards to the players - the first argument is the hostname (IP address) of the server - typically 127.0.0.1.

And if you have a .bat file for the ACPC dealer, I am happy to include that into the repo, so Windows users don't have to replicate that as well.
